spring:
  application:
    name: "FashionShop-Backend-API"
  datasource:
    url: jdbc:postgresql://localhost:5430/fashionshop
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  redis:
    host: localhost
    port: 6379

minio:
  host: localhost
  port: 9000
  key:
    access: psuEXGWwKAoytjPmm6pN
    secret: V4xaeDC3oX9mEeC3KNtyIE8RZqXaRrc7jGb1y7ib

server:
  port: 8080