spring:
  application:
    name: "FashionShop-Backend-API"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080