spring:
  application:
    name: "FashionShop-Backend-API"
  datasource:
    url: jdbc:postgresql://localhost:5430/fashionshop
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
  redis:
    host: localhost
    port: 6379
  mail:
    port: 587
    host: smtp.gmail.com
    password: xxxx
    username: xxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
minio:
  host: localhost
  port: 9000
  key:
    # Phong
    access: psuEXGWwKAoytjPmm6pN
    secret: V4xaeDC3oX9mEeC3KNtyIE8RZqXaRrc7jGb1y7ib

#    #Tri Anh
#    access: OmeI3K75ARVyaLHiW9Ms
#    secret: d8GG52DsslPZIP1jcfVMofYVxHfv9H4jjTtJ8wZ8

jwt:
  secret: V4xaeDC3oX9mEeC3KNtyIE8RZqXaRrc7jGb1y7ib
server:
  port: 8080