spring:
  application:
    name: "FashionShop-Backend-API"
  datasource:
    url: jdbc:postgresql://localhost:5430/fashionshop
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080